# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rack", ">= 3.0"
gem "rackup"
gem 'honeycomb-beeline', path: "../.."
